### ISSUE TITLE
BUG: Foutmelding bij push en pull commit

### ISSUE THREAD

**Issue by CarlijnPelk** [emmaus-6v/2122-6V-Knikkerbaan-groep-7#20]
@cam-emmauscollege

Ik krijg deze foutmelding wanneer ik een commit wil pushen. Weet u hoe ik dit kan oplossen?

![image](https://user-images.githubusercontent.com/57983434/154664385-6123bb3e-11ac-4f64-aae8-d6638755c216.png)

Dit zie ik wanneer ik op **Open Git Log** klik:

![image](https://user-images.githubusercontent.com/57983434/154664584-28ef918d-0dde-47d7-a147-1b9f501a9a40.png)

Dit zie ik wanneer ik op **Show Command Output** klik:

![image](https://user-images.githubusercontent.com/57983434/154664748-91fb4b7e-42ae-42b4-836a-29403aa4cae8.png)

**Comment by cam-emmauscollege** [comment]
Blijkbaar ben jij verder gegaan met code terwijl er al een nieuwere versie van de code op GitHub stond. Nu jij jouw code naar GitHub wilt sturen, gaat hij moeilijk doen. Als je links onderin op "GitPod" klikt, krijg je een menuutje. Kies daarin 'GitPod: Share running workspace'. Geef mij even een seintje als je dat hebt gedaan, dan probeer ik het voor je op te lossen.

**Comment by CarlijnPelk** [comment]
> Blijkbaar ben jij verder gegaan met code terwijl er al een nieuwere versie van de code op GitHub stond. Nu jij jouw code naar GitHub wilt sturen, gaat hij moeilijk doen. Als je links onderin op "GitPod" klikt, krijg je een menuutje. Kies daarin 'GitPod: Share running workspace'. Geef mij even een seintje als je dat hebt gedaan, dan probeer ik het voor je op te lossen.

Oh, dankuwel voor u antwoord. ik heb nu de code opnieuw in gitpod geladen (via gitpod.io/# enz) en de veranderingen die ik had gemaakt hieraan toegevoegd (het was niet zo veel). Dit kon ik wel pushen dus volgens mij is het zo opgelost.

**Comment by cam-emmauscollege** [comment]
Fijn!

Verstuurd vanaf mijn iPhone
